[package]
name = "ruffle_desktop"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
default-run = "ruffle_desktop"

[dependencies]
cpal = "0.11.0"
ruffle_core = { path = "../core" }
glium = "0.26.0-alpha5"
glutin = "0.22.0-alpha5"
env_logger = "0.7.1"
generational-arena = "0.2.7"
image = "0.22.3"
jpeg-decoder = "0.1.18"
log = "0.4"
lyon = "0.15.5"
sample = "0.10.0"
structopt = "0.3.7"
winit = "0.20.0"
webbrowser = "0.5.2"
url = "2.1.1"

[features]
avm_debug = ["ruffle_core/avm_debug"]
